language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: S33ZH16zEnR5WaOnkEnjHVhAMlyVUuwMyh4Vmwluc6HpXQAacw4bUg3mM5dvxyFEef2B2sAjirNbOXsBMpy8CxgZvFVzCJBs4/ic3zPYmOdFRgMNP+G3lMCPyB8XXGBYAKwMmY3+GqOfYzfTJ+7IASW9twRHWHF39iTaoX1HhYKCd1tzgHPg6K8QIN4Oy4E/eawxltEQH37KogpsNl1cPwtm5rh/gCz3LFsfywnp92F9QnzppQZYk2cJqs+ionrm+32jx77d+wIuNK/TZ36eH9kWg5IRFnElQcSwArm0uEqkBjRiBal3pr+I/8c7D8RRG435VH7Oq5hZ22QKQlioUoDcaeE+bmryoG/UDG5ngSB/MeIgFM6wJBtT4YHRShWmX2WJfy5g/WPSN3eYSQz0azSMdMJIN4OpBcSmgcyEYniXNeIoXwc6xzOw+mp9hS13N4P5NHVY+7Fg+F+M0x5pIcVynDpk4CUA4lHjKHIszZlmX9uMHrhHKcEQR8MyXpvzZq4J59fXQllvMgEhoUg9mT2mGsMF1PzLaPuRbsaKBbGVSuW3KWCn4gvU8BTZezrUS3DlLEy2JnHwPkw1llKg3oi8wnRlX3jcR1b3bjjyRjtG4ASeln8PlyB6KlS9HUgT//2jdKSuNySA1QnO+GFaA2fFDBEB7Vzh91capNCtaCQ=
  app: nameless-bayou-38988



